version: '3.7'
services:
  esbbw6jenkins:
    build:
      dockerfile: Dockerfile
      context: .
    networks: 
        - bw6demo_net
    container_name: bw6jenkins
    ports:
        - '8082:8080'
        - '50002:50000'
    volumes:
        - bw6jenkins_data::/var/cloudbees-jenkins-distribution
#    environment: 
#        - JAVA_OPTS="-Xms1G -Xmx2G -XX:+UseG1GC"

  esbbw6artifactory:
    image: 'docker.bintray.io/jfrog/artifactory-oss:6.17.0'
    networks: 
        - bw6demo_net
    container_name: bw6artifactory
    ports:
        - '8081:8081'
    volumes:
        - bw6artifactory_data:/var/opt/jfrog/artifactory
#    Add extra Java options by uncommenting the following line
#    environment:
#        - EXTRA_JAVA_OPTIONS="-Xms512m -Xmx4g"
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000

volumes:
    bw6jenkins_data:
    bw6artifactory_data:
networks:
    bw6demo_net: